export type AgentHarnessRoute = 'thread' | 'providers'

/**
 * T3 remains responsible for chat rendering, model selection, approvals, plan
 * mode, turn controls, and the thread list. Cate owns every surrounding project
 * surface, so the embedded guest hides T3's project navigation and utilities.
 *
 * These selectors intentionally use upstream data attributes instead of class
 * names. Class names are generated by Tailwind and are much more likely to move
 * during an upstream update.
 */
export const AGENT_CHAT_ONLY_CSS = `
[data-sidebar="trigger"],
[data-slot="sidebar-header"],
[data-slot="sidebar-footer"],
a[aria-label="Go to threads"]:has(svg[aria-label="T3"]),
svg[aria-label="T3"],
[data-workspace-titlebar-controls],
[data-composer-context-control],
[data-preview-panel-mode],
[data-preview-mini-player],
[data-terminal-owner],
[data-right-panel-tabbar],
[data-right-panel-surface-content],
button[aria-label="Open diff"] {
  display: none !important;
}

[data-sidebar="group"] > div:has(> button[aria-label="Filter threads by project"]),
button[aria-label="Filter threads by project"],
button[aria-label="New project"],
[data-slot="composer-context-strip"] {
  display: none !important;
}

[data-slot="composer-shell"][data-with-context="true"]::before,
[data-slot="composer-shell"][data-with-context="true"] [data-slot="composer-host"]::after,
[data-slot="composer-shell"][data-with-context="true"] [data-chat-composer-main-surface]::after {
  clip-path: none !important;
  border-radius: 22px !important;
}

[data-slot="sidebar-inset"] {
  min-width: 0 !important;
  margin: 0 !important;
  border-radius: 0 !important;
}

[data-chat-header] {
  display: none !important;
}

a[href^="/pull-requests"],
a[href*="/projects/"],
a[href*="/worktrees/"],
a[href*="/branches/"],
a[href^="/settings/"]:not([href^="/settings/providers"]),
a[href^="/usage"] {
  display: none !important;
}
`

/** Remove upstream product chrome from the embedded guest. Provider settings
 * also receive neutral host copy, while thread content is never rewritten. */
export function agentHarnessBrandingScript(route: AgentHarnessRoute): string {
  return `(() => {
    const hostCopy = (value) => value.replace(/\\bT3(?: Code|Code)?\\b/g, 'Cate Agent')
    const rewriteChrome = (root) => {
      const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT)
      let node
      while ((node = walker.nextNode())) {
        if (node.parentElement?.closest('script, style, template, pre, code, textarea, [contenteditable], [data-message-id], [data-message-role]')) continue
        const next = hostCopy(node.nodeValue || '')
        if (next !== node.nodeValue) node.nodeValue = next
      }
    }
    const removeProductChrome = () => {
      if (document.title !== 'Cate Agent') document.title = 'Cate Agent'
      document.querySelectorAll('a[aria-label="Go to threads"]:has(svg[aria-label="T3"]), svg[aria-label="T3"]').forEach((element) => element.remove())
      // Restrict copy changes to product chrome, never the conversation body.
      document.querySelectorAll('[data-sonner-toast], [role="tooltip"], [role="menu"], [data-slot="sidebar-footer"], [data-slot="sidebar-header"]').forEach(rewriteChrome)
      document.querySelectorAll('button[title], button[aria-label], input[placeholder], textarea[placeholder]').forEach((element) => {
        for (const attribute of ['title', 'aria-label', 'placeholder']) {
          const value = element.getAttribute(attribute)
          if (value && hostCopy(value) !== value) element.setAttribute(attribute, hostCopy(value))
        }
      })
    }
    removeProductChrome()
    new MutationObserver(removeProductChrome).observe(document.documentElement, {
      childList: true,
      subtree: true,
      characterData: true,
    })
    if (${JSON.stringify(route)} !== 'providers') return

    const rewrite = (root) => {
      const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT)
      let node
      while ((node = walker.nextNode())) {
        const parent = node.parentElement
        if (!parent || parent.closest('script, style, template')) continue
        if (node.nodeValue?.includes('T3 Code')) {
          node.nodeValue = hostCopy(node.nodeValue)
        }
      }
    }
    rewrite(document.body)
    new MutationObserver((mutations) => {
      for (const mutation of mutations) {
        for (const added of mutation.addedNodes) rewrite(added)
      }
    }).observe(document.body, { childList: true, subtree: true })
  })()`
}

function pathParts(url: URL): string[] {
  return url.pathname.split('/').filter(Boolean).map((part) => decodeURIComponent(part))
}

/** Provider settings requested from an embedded thread are handed to Cate's
 * settings window instead of replacing the chat inside the panel. */
export function isAgentProviderSettingsNavigation(candidate: string, harnessUrl: string): boolean {
  try {
    const next = new URL(candidate)
    const harness = new URL(harnessUrl)
    const parts = pathParts(next)
    return next.origin === harness.origin && parts[0] === 'settings' && parts[1] === 'providers'
  } catch {
    return false
  }
}

/** Only the pairing bootstrap, new-thread surfaces, threads in the bound
 * environment, and the provider settings page may replace the embedded guest's
 * top-level document. */
export function isAllowedAgentHarnessNavigation(
  candidate: string,
  harnessUrl: string,
  environmentId: string | null,
  route: AgentHarnessRoute,
  expectedThreadId?: string,
): boolean {
  try {
    const next = new URL(candidate)
    const harness = new URL(harnessUrl)
    if (next.origin !== harness.origin) return false

    const parts = pathParts(next)
    if (parts.length === 1 && parts[0] === 'pair') return true
    if (parts[0] === 'settings' && parts[1] === 'providers') return route === 'providers'
    if (route === 'providers') return false
    if (parts.length === 0) return !expectedThreadId
    if (parts[0] === 'draft' && parts.length === 2) return true
    return !!environmentId && parts[0] === environmentId && parts.length === 2
  } catch {
    return false
  }
}

/** Read the durable thread id from T3's /:environmentId/:threadId route. */
export function agentThreadIdFromUrl(url: string, environmentId: string | null): string | null {
  if (!environmentId) return null
  try {
    const parts = pathParts(new URL(url))
    return parts.length === 2 && parts[0] === environmentId ? parts[1] : null
  } catch {
    return null
  }
}
