export { createFsClient, fsClient, type FsClient, type ImportSource, type ByteSource, type ContentSearch } from './fsClient'
export { createWatchManager, watchManager, watchFsRoot, type WatchManager, type FsWatchListener } from './watchManager'
export { attachBuffer, type AttachedBuffer } from './bufferClient'
export { recordRecentFile, getRecentFiles } from './recentFiles'
export { createFileRefs, fileRefs, type FileRefs, type RefFs, type RefTarget } from './fileRefs'
export { FileTreeModel, type DroppedImport, type FileTreeFs, type FileTreeModelOptions, type FileTreeSavedState, type FileTreeSnapshot } from './fileTreeModel'
export { createExplorerRefresh } from './explorerRefresh'
export { createSearchRunner, type SearchRunner, type SearchRunnerOptions, type SearchRunState, type SearchRunStore } from './searchRunner'
export { acquireBufferText, type SharedBufferText } from './bufferText'
