export { createFsClient, fsClient, type FsClient, type ImportSource, type ByteSource, type ContentSearch } from './fsClient'
export { createWatchManager, watchManager, watchFsRoot, type WatchManager, type FsWatchListener } from './watchManager'
export { attachBuffer, type AttachedBuffer } from './bufferClient'
export { recordRecentFile, getRecentFiles } from './recentFiles'
export { createFileRefs, fileRefs, type FileRefs, type RefFs, type RefTarget } from './fileRefs'
export { acquireBufferText, type SharedBufferText } from './bufferText'
